services:
  geodb:
    image: postgis/postgis:16-3.4
    container_name: postgis_db
    environment:
      POSTGRES_DB: partner
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: partner_app
    depends_on:
      - geodb
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://geodb:5432/partner
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: password
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
      QUARKUS_PROFILE: prod
    ports:
      - "8080:8080"
    # Se precisar recompilar dentro do container:
    # build:
    #   context: .
    #   dockerfile: src/main/docker/Dockerfile.jvm
    # environment:
    #   QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://user:password@geodb:5432/partner

volumes:
  postgis_data:
